name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Benchmark
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Build Package
        run: yarn build
      - name: Run Benchmarks
        env:
          DEEPDAO_API_KEY: ${{ secrets.DEEPDAO_API_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
          CNVSEC_ID: ${{ secrets.CNVSEC_ID }}
        run: yarn bench
